# bundle exec solr_wrapper -i solr-test -p 8983 -n test-core -n test-core -d solr/conf --persist --version 5.5.4
instance_dir: solr-test
port: 8983
persist: true
managed: true
version: 5.5.4
collection:
  name: <% if ENV['RAILS_ENV'] == 'test' %>test-core<% else %>development-code<% end %>
  dir: 'solr/conf'
