language: ruby

services:
  - memcached

env: FINDINGAIDS_FULL_HOST="dlib.nyu.edu" FINDINGAIDS_FULL_PATH="/findingaids/html" FINDINGAIDS_FULL_DEFAULT_EXTENSION="html"

rvm:
  - 2.2.6
  - 2.3.3

before_script:
  - mysql -e 'create database findingaids_test;'
  - RAILS_ENV=test bundle exec rake db:schema:load
  - bundle exec rake findingaids:jetty:install
  - bundle exec rake jetty:start
  - sleep 10

after_script:
  - bundle exec rake jetty:stop

bundler_args: --without development

script: "RAILS_ENV=test MAX_WAIT=60 bundle exec rake"

notifications:
  email:
    - lib-webservices@nyu.edu

sudo: false
