# machine:
#   services:
#     - docker
#
# dependencies:
#   override:
#     - docker-compose version
#     - docker-compose up -d
#     - docker-compose run web rake db:create
#     - docker-compose run -e RAILS_ENV=test web rake db:schema:load
#
# database:
#   override:
#     - echo "Database running in docker..."
#
# test:
#   override:
#     - docker-compose run -e RAILS_ENV=test web rake
version: 2
jobs:
  build:
    working_directory: /root/findingaids
    steps:
      - run:
        name: Install Docker Compose
        command: |
          set -x
          curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
      - run: apt-get -qq update; apt-get -y install git
      - checkout
      - run:
          name: Docker Compose Up
          command: docker-compose up -d
      - run:
          name: Create Test DB
          command: |
            docker-compose run web rake db:create
            docker-compose run -e RAILS_ENV=test web rake db:schema:load
      - run:
          name: Run tests
          command: docker-compose run -e RAILS_ENV=test web rake
