version: '3'
services:

  dev:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - test.env
    command: "tail -f /dev/null"
    depends_on:
      - setup_dbs

  setup_dbs:
    build: .
    env_file:
      - test.env
    command: bash -c "sleep 5; rake db:setup"
    depends_on:
      - solr
      - db

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      RAILS_ENV: test
      CI:
      CODECLIMATE_REPO_TOKEN:
      COVERALLS_REPO_TOKEN:
    env_file:
      - test.env
    command: "tail -f /dev/null"
    depends_on:
      - setup_test_dbs

  setup_test_dbs:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      RAILS_ENV: test
    env_file:
      - test.env
    command: bash -c "sleep 5; rake db:setup"
    depends_on:
      - solr
      - db

  db:
    image: library/mysql:5.6.22
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  solr:
    image: nyulibraries/solr-test:5.5.4
    expose:
      - "8983"
