version: '3.6'

x-build_default: &build_default
  image: findingaids
  build:
    context: .
    args:
      - AQUA_MICROSCANNER_TOKEN
    cache_from:
      - ruby:2.3.7-alpine
      - findingaids
      - nyulibraries/findingaids:${BRANCH_NO_SLASH}
      - nyulibraries/findingaids:latest

x-build_test: &build_test
  image: findingaids_test
  build:
    context: .
    dockerfile: Dockerfile.test
    cache_from:
      - nyulibraries/selenium_chrome_headless_ruby:2.3.7-slim-chrome_69
      - findingaids_test
      - nyulibraries/findingaids_test:${BRANCH_NO_SLASH}
      - nyulibraries/findingaids_test:latest

services:

  dev:
    <<: *build_default
    ports:
      - "9292:9292"
    env_file:
      - test.env
    command: ["./script/start.sh", "development"]

  test:
    <<: *build_test
    environment:
      RAILS_ENV: test
      CI:
      CODECLIMATE_REPO_TOKEN:
      COVERALLS_REPO_TOKEN:
      SOLR_URL: http://solr:8983/solr/test-core
    env_file:
      - test.env
    command: ["bundle", "exec", "rake"]
    depends_on:
      - setup_test_dbs

  setup_test_dbs:
    <<: *build_test
    environment:
      RAILS_ENV: test
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "solr:8983", "--", "rake", "db:setup"]
    depends_on:
      - db
      - solr

  setup_dbs:
    <<: *build_test
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "solr:8983", "--", "rake", "db:setup"]
    depends_on:
      - db
      - solr

  db:
    image: library/mysql:5.6.22
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  solr:
    image: nyulibraries/specialcollections-solr:test
