version: '3.2'
services:

  dev:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - bundle_cache:/bundle
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "solr:8983", "--", "bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
    depends_on:
      - setup_dbs

  reindex:
    build:
      context: .
      args:
        reindex_env: "true"
    environment:
      FINDINGAIDS_LOG: STDOUT
      SOLR_URL:
      SECRET_KEY_BASE:
      RAILS_ENV:
    command: "tail -f /dev/null"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - bundle_cache:/bundle
    environment:
      RAILS_ENV: test
      CI:
      CODECLIMATE_REPO_TOKEN:
      COVERALLS_REPO_TOKEN:
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "solr:8983", "--", "rake"]
    depends_on:
      - setup_test_dbs

  setup_test_dbs:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - bundle_cache:/bundle
    environment:
      RAILS_ENV: test
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "solr:8983", "--", "rake", "db:setup"]
    depends_on:
      - db
      - solr

  setup_dbs:
    build: .
    volumes:
      - bundle_cache:/bundle
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "solr:8983", "--", "rake", "db:setup"]
    depends_on:
      - db
      - solr

  db:
    image: library/mysql:5.6.22
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  solr:
    image: nyulibraries/specialcollections-solr:test
    expose:
      - "8983"

volumes:
  bundle_cache:
