version: '3.6'
services:

  dev:
    image: findingaids
    build:
      context: .
      cache_from:
        - ruby:2.3.7-alpine
        - findingaids
        - nyulibraries/findingaids:${BRANCH_NO_SLASH}
        - nyulibraries/findingaids:latest
    ports:
      - "9292:9292"
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "solr:8983", "--", "./script/start.sh", "development"]
    depends_on:
      - setup_dbs

  setup_dbs:
    image: findingaids
    build:
      context: .
      cache_from:
        - ruby:2.3.7-alpine
        - findingaids
        - nyulibraries/findingaids:${BRANCH_NO_SLASH}
        - nyulibraries/findingaids:latest
    env_file:
      - test.env
    command: bash -c "sleep 5; rake db:setup"
    depends_on:
      - solr
      - db

  deploy_dev_assets:
    image: findingaids_test
    build:
      context: .
      dockerfile: Dockerfile.test
      cache_from:
        - ruby:2.3.7-alpine
        - findingaids_test
        - nyulibraries/findingaids_test:${BRANCH_NO_SLASH}
        - nyulibraries/findingaids_test:latest
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      RAILS_ENV: "staging"
      SECRET_KEY_BASE:
    command: "bundle exec rake assets:precompile && aws s3 sync public/assets s3://cdn-dev.library.nyu.edu/specialcollections --delete"

  deploy_prod_assets:
    image: findingaids_test
    build:
      context: .
      dockerfile: Dockerfile.test
      cache_from:
        - ruby:2.3.7-alpine
        - findingaids_test
        - nyulibraries/findingaids_test:${BRANCH_NO_SLASH}
        - nyulibraries/findingaids_test:latest
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      RAILS_ENV: "production"
      SECRET_KEY_BASE:
    command: "bundle exec rake assets:precompile && aws s3 sync public/assets s3://cdn.library.nyu.edu/specialcollections --delete"

  test:
    image: findingaids_test
    build:
      context: .
      dockerfile: Dockerfile.test
      cache_from:
        - ruby:2.3.7-alpine
        - findingaids_test
        - nyulibraries/findingaids_test:${BRANCH_NO_SLASH}
        - nyulibraries/findingaids_test:latest
    environment:
      RAILS_ENV: test
      CI:
      CODECLIMATE_REPO_TOKEN:
      COVERALLS_REPO_TOKEN:
      SOLR_URL: http://solr:8983/solr/test-core
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "solr:8983", "--", "rake"]
    depends_on:
      - setup_test_dbs

  setup_test_dbs:
    image: findingaids_test
    build:
      context: .
      dockerfile: Dockerfile.test
      cache_from:
        - ruby:2.3.7-alpine
        - findingaids_test
        - nyulibraries/findingaids_test:${BRANCH_NO_SLASH}
        - nyulibraries/findingaids_test:latest
    environment:
      RAILS_ENV: test
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "solr:8983", "--", "rake", "db:setup"]
    depends_on:
      - db
      - solr

  setup_dbs:
    image: findingaids
    build:
      context: .
      cache_from:
        - ruby:2.3.7-alpine
        - findingaids
        - nyulibraries/findingaids:${BRANCH_NO_SLASH}
        - nyulibraries/findingaids:latest
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "solr:8983", "--", "rake", "db:setup"]
    depends_on:
      - db
      - solr

  db:
    image: library/mysql:5.6.22
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  solr:
    image: nyulibraries/specialcollections-solr:test

volumes:
  bundle_cache:
