version: '3'
services:

  unicorn:
    build: .
    ports:
      - "5000:5000"
    # volumes:
    #   - .:/app
    environment:
      UNICORN_PORT: "5000"
      RAILS_ENV: "staging"
      LOG_LEVEL: "debug"
      ASSET_HOST: "https://cdn-dev.library.nyu.edu/specialcollections"
    env_file:
      - test.env
    command: "./script/start.sh staging"
    depends_on:
      - setup_dbs

  deploy_dev_assets:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      RAILS_ENV: "staging"
    command: "bundle exec rake assets:precompile && aws s3 sync public/assets s3://cdn-dev.library.nyu.edu/specialcollections --delete"

  deploy_prod_assets:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      RAILS_ENV: "production"
    command: "bundle exec rake assets:precompile && aws s3 sync public/assets s3://cdn.library.nyu.edu/specialcollections --delete"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - unicorn

  setup_dbs:
    build: .
    env_file:
      - test.env
    command: bash -c "sleep 5; rake db:setup"
    depends_on:
      - solr
      - db

  db:
    image: library/mysql:5.6.22

    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  solr:
    image: nyulibraries/specialcollections-solr:test
    entrypoint: "docker-entrypoint.sh"
    command: "solr-foreground"
