web:
  extends:
    file: docker-compose.yml
    service: web
  links:
    - db
  environment:
    FINDINGAIDS_DB_HOST: db
    FINDINGAIDS_FULL_HOST: dlib.nyu.edu
    FINDINGAIDS_FULL_PATH: /findingaids/html
    FINDINGAIDS_FULL_DEFAULT_EXTENSION: html
    MAX_WAIT: 60
    RAILS_ENV: test
db:
  image: library/mysql:5.6.22
  ports:
    - "13306:3306"
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
