version: 2
jobs:
  build:
    docker:
      - image: nyulibraries/circleci
      - image: library/mysql:5.6.22
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      - image: nyulibraries/solr-test:5.5.4
    working_directory: /root/findingaids
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Create Test DB
          command: |
            rake db:create
            RAILS_ENV=test rake db:schema:load
      - run:
          name: Run tests
          command: RAILS_ENV=test web rake
