docker-defaults: &docker-defaults
  docker:
    - image: nyulibraries/circleci_docker:18.06.1-ce-git
  working_directory: ~/app

test: &test
  run:
    name: Test
    command: docker-compose run test

version: 2
jobs:
  deploy-dev:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *test
      - run:
          name: Deploy into staging via Jenkins
          command: |
            docker run --rm appropriate/curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/Finding%20Aids/job/Finding%20Aids%20Development%20Deploy/build/api

  deploy-prod:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *test
      - run:
          name: Deploy into production via Jenkins
          command: |
            docker run --rm appropriate/curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/Finding%20Aids/job/Finding%20Aids%20Production%20Deploy/build/api

  reindex_changed_since_yesterday:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          no_output_timeout: 5h
          name: Reindex EADS changed in past 24 hours into production index
          command: |
            export RAILS_ENV=production
            export SOLR_URL=$SHARED_SOLR_URL
            export SECRET_KEY_BASE=$PRODUCTION_SECRET_KEY_BASE
            docker-compose run reindex rake ead_indexer:reindex_changed_since_yesterday

  reindex_changed:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          no_output_timeout: 2h
          name: Reindex EAD changed in the last commit
          command: |
            export RAILS_ENV=production
            export SOLR_URL=$SHARED_SOLR_URL
            export SECRET_KEY_BASE=$PRODUCTION_SECRET_KEY_BASE
            docker-compose run reindex rake ead_indexer:reindex_changed

  reindex_single_ead:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          no_output_timeout: 1h
          name: Reindex EAD changed in the last commit
          command: |
            export RAILS_ENV=production
            export SOLR_URL=$SHARED_SOLR_URL
            export SECRET_KEY_BASE=$PRODUCTION_SECRET_KEY_BASE
            export EAD=test
            docker-compose run reindex rake ead_indexer:index EAD=$EAD

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - deploy-dev:
          filters:
            branches:
              ignore:
                - master
                - feature/move_crons_to_circle
      - deploy-prod:
          filters:
            branches:
              only: master
  reindex_nightly:
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - feature/move_crons_to_circle
    jobs:
      - reindex_changed_since_yesterday
