docker-defaults: &docker-defaults
  docker:
    - image: docker:18.03.0-ce-git
  working_directory: ~/app

dc-setup: &dc-setup
  run:
    name: Setup docker-compose dependency
    command: |
      apk add --no-cache python3
      pip3 install docker-compose==1.20.1

test: &test
  run:
    name: Test
    command: docker-compose run test

version: 2
jobs:
  deploy-dev:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *dc-setup
      - <<: *test
      - run:
          name: Deploy into staging via Jenkins
          command: |
            docker run --rm appropriate/curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/Finding%20Aids/job/Finding%20Aids%20Development%20Deploy/build/api

  deploy-prod:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *dc-setup
      - <<: *test
      - run:
          name: Deploy into production via Jenkins
          command: |
            docker run --rm appropriate/curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/Finding%20Aids/job/Finding%20Aids%20Production%20Deploy/build/api

  reindex_changed_since_yesterday:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *dc-setup
      - run:
          name: Reindex EADS changed in past 24 hours
          command: |
            docker-compose run -d --name findingaids_reindex reindex
            docker exec findingaids_reindex git clone https://github.com/NYULibraries/findingaids_eads.git findingaids_eads
            docker exec -e "RAILS_ENV=production" -e "SOLR_URL=$PRODUCTION_SOLR_URL" -e "SECRET_KEY_BASE=$PRODUCTION_SECRET_KEY_BASE" findingaids_reindex rake ead_indexer:reindex_changed_since_yesterday

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - deploy-dev:
          filters:
            branches:
              ignore: master
      - deploy-prod:
          filters:
            branches:
              only: master
  reindex_nightly:
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - feature/move_crons_to_circle
    jobs:
      - reindex_changed_since_yesterday
