version: 2
jobs:
  build:
    docker:
      - image: barnabyalter/circleci
    working_directory: /root/findingaids
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Docker Compose Up
          command: docker-compose up -d
      - run:
          name: Create Test DB
          command: |
            docker-compose run web rake db:create
            docker-compose run -e RAILS_ENV=test web rake db:schema:load
      - run:
          name: Run tests
          command: docker-compose run -e RAILS_ENV=test web rake
