docker-defaults: &docker-defaults
  docker:
    - image: nyulibraries/circleci_docker:18.06.1-ce-git-compose-1.22.0
  working_directory: ~/app

pull_docker: &pull_docker
  run:
    name: Pull Docker
    command: |
      docker pull nyulibraries/specialcollections:${CIRCLE_BRANCH//\//_} || docker pull nyulibraries/specialcollections:latest
      docker pull nyulibraries/specialcollections_test:${CIRCLE_BRANCH//\//_} || docker pull nyulibraries/specialcollections_test:latest

build_docker: &build_docker
  run:
    name: Build Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker-compose build

test: &test
  run:
    name: Test
    command: docker-compose run test

push_docker: &push_docker
  run:
    name: Push Docker
    command: |
      docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
      script/docker/push_dockerhub.sh
      script/docker/push_quay.sh

version: 2
jobs:
  test-and-build-image:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *pull_docker
      - <<: *build_docker
      - <<: *test
      - <<: *push_docker

  deploy-dev:
    docker:
      - image: appropriate/curl
    steps:
      - run:
          name: Deploy into staging via Jenkins
          command: |
            curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/Finding%20Aids/job/Finding%20Aids%20Development%20Deploy/build/api
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            curl -u $JENKINS_STAGE_USERNAME:$JENKINS_STAGE_API_KEY -X POST https://jenkinsapi-dev.library.nyu.edu/job/SpecialCollections%20Development%20Deploy/build/api --data-urlencode json="{\"parameter\": [{\"name\":\"TAG\", \"value\":\"${BRANCH_NO_SLASH}-${CIRCLE_SHA1}\"}]}"

  deploy-prod:
    docker:
      - image: appropriate/curl
    steps:
      - run:
          name: Deploy into production via Jenkins
          command: |
            curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/Finding%20Aids/job/Finding%20Aids%20Production%20Deploy/build/api
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            #curl -u $JENKINS_PROD_USERNAME:$JENKINS_PROD_API_KEY -X POST https://jenkinsapi.library.nyu.edu/job/SpecialCollections%20Production%20Deploy/build/api --data-urlencode json="{\"parameter\": [{\"name\":\"TAG\", \"value\":\"${BRANCH_NO_SLASH}-${CIRCLE_SHA1}\"}]}"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test-and-build-image
      - deploy-dev:
          requires:
              - test-and-build-image
          filters:
            branches:
              ignore: master
      - deploy-prod:
          requires:
              - test-and-build-image
          filters:
            branches:
              only: master
