docker-defaults: &docker-defaults
  docker:
    - image: nyulibraries/circleci_docker:18.06.1-ce-git-compose-1.22.0
  working_directory: ~/app

pull_docker: &pull_docker
  run:
    name: Pull Docker
    command: |
      docker pull nyulibraries/findingaids:${CIRCLE_BRANCH//\//_} || docker pull nyulibraries/findingaids:latest
      docker pull nyulibraries/findingaids_test:${CIRCLE_BRANCH//\//_} || docker pull nyulibraries/findingaids_test:latest

build_docker: &build_docker
  run:
    name: Build Docker
    command: |
      export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
      docker-compose build

test: &test
  run:
    name: Test
    command: docker-compose run test

push_docker: &push_docker
  run:
    name: Push Docker
    command: |
      docker tag findingaids nyulibraries/findingaids:${CIRCLE_BRANCH//\//_}
      docker tag findingaids nyulibraries/findingaids:${CIRCLE_BRANCH//\//_}-${CIRCLE_SHA1}
      docker tag findingaids nyulibraries/findingaids:latest
      docker tag findingaids_test nyulibraries/findingaids_test:${CIRCLE_BRANCH//\//_}
      docker tag findingaids_test nyulibraries/findingaids_test:${CIRCLE_BRANCH//\//_}-${CIRCLE_SHA1}
      docker tag findingaids_test nyulibraries/findingaids_test:latest
      docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
      docker push nyulibraries/findingaids:${CIRCLE_BRANCH//\//_}
      docker push nyulibraries/findingaids:${CIRCLE_BRANCH//\//_}-${CIRCLE_SHA1}
      docker push nyulibraries/findingaids:latest
      docker push nyulibraries/findingaids_test:${CIRCLE_BRANCH//\//_}
      docker push nyulibraries/findingaids_test:${CIRCLE_BRANCH//\//_}-${CIRCLE_SHA1}
      docker push nyulibraries/findingaids_test:latest

version: 2
jobs:
  deploy-dev:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *build_docker
      - <<: *test
      - <<: *push_docker
      - run:
          name: Deploy into staging via Jenkins
          command: |
            docker run --rm appropriate/curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/Finding%20Aids/job/Finding%20Aids%20Development%20Deploy/build/api

  deploy-prod:
    <<: *docker-defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *build_docker
      - <<: *test
      - <<: *push_docker
      - run:
          name: Deploy into production via Jenkins
          command: |
            docker run --rm appropriate/curl -u $JENKINS_USERNAME:$JENKINS_API_KEY -X POST http://jenkins.library.nyu.edu/view/Finding%20Aids/job/Finding%20Aids%20Production%20Deploy/build/api

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - deploy-dev:
          filters:
            branches:
              ignore: master
      - deploy-prod:
          filters:
            branches:
              only: master
