version: 2
jobs:
  build:
    docker:
      - image: nyulibraries/circleci
      - image: nyulibraries/solr-test:5.5.4
      - image: nyulibraries/rails:4.2
      - image: library/mysql:5.6.22
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    working_directory: /root/findingaids
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Create Test DB
          command: |
            docker run --rm nyulibraries/rails:4.2 rake db:create
            docker run -e RAILS_ENV=test --rm nyulibraries/rails:4.2 rake db:schema:load
      - run:
          name: Run tests
          command: docker run -e RAILS_ENV=test --rm nyulibraries/rails:4.2 rake
