Catalog:
  repositories:
    fales:
      display: 'The Fales Library & Special Collections'
      url: "fales"
      admin_code: fales
    tamwag:
      display: 'The Tamiment Library & Robert F. Wagner Labor Archives'
      url: "tamiment"
      admin_code: "tamwag"
    archives:
      display: 'New York University Archives'
      url: "universityarchives"
      admin_code: "archives"
    nyhs:
      display: 'New-York Historical Society'
      url: "nyhistory"
      admin_code: "nyhs"
    bhs:
      display: 'Brooklyn Historical Society'
      url: "brooklynhistory"
      admin_code: "bhs"
    poly:
      display: 'Poly Archives'
      url: "poly"
      admin_code: "poly"
    rism:
      display: 'Research Institue for the Study of Man'
      url: "rism"
      admin_code: "rism"