Catalog:
  repositories:
    all:
      display: 'All Collections'
      url: ""
      admin_code: ""
    fales:
      display: 'The Fales Library'
      url: "fales"
      admin_code: fales
    tamwag:
      display: 'The Tamiment Library'
      url: "tamwag"
      admin_code: "tamwag"
    archives:
      display: 'New York University Archives'
      url: "archives"
      admin_code: "archives"
    nyhs:
      display: 'New-York Historical Society'
      url: "nyhs"
      admin_code: "nyhs"
    bhs:
      display: 'Brooklyn Historical Society'
      url: "bhs"
      admin_code: "bhs"