Catalog:
  repositories:
    fales:
      display: 'The Fales Library & Special Collections'
      url: "fales"
      admin_code: fales
    tamiment:
      display: 'The Tamiment Library & Robert F. Wagner Labor Archives'
      url: "tamiment"
      admin_code: "tamiment"
    universityarchives:
      display: 'New York University Archives'
      url: "universityarchives"
      admin_code: "universityarchives"
    nyhistory:
      display: 'New-York Historical Society'
      url: "nyhistory"
      admin_code: "nyhistory"
    brooklynhistory:
      display: 'Brooklyn Historical Society'
      url: "brooklynhistory"
      admin_code: "brooklynhistory"
    poly:
      display: 'Poly Archives'
      url: "poly"
      admin_code: "poly"
    rism:
      display: 'Research Institue for the Study of Man'
      url: "rism"
      admin_code: "rism"