default: &default
  adapter: solr
development:
  <<: *default
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/development-core" %>
test: &test
  <<: *default
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/solr/test-core" %>
staging: &staging
  <<: *default
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr" %>
production:
  <<: *staging
